name: Laura Gilchrist
favicon: null
layout_spectrum: 0.24831
typography_spectrum: 0.61102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3d3b3c'
    - '#84693e'
    - '#f8d35b'
  brandStrength: 0.5
  lightness: 0.5881772506982088
  saturation: 0.375
  rhythmicContrast: 0.45013704779557884
purpose: []
