name: Laura Gilchrist
favicon: null
layout_spectrum: 0
typography_spectrum: 0.61102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#0f0c05'
    - '#7e91a9'
    - '#4e3c17'
    - '#e9a825'
  brandStrength: 0.3125
  lightness: 0.5881772506982088
  saturation: 0.375
  rhythmicContrast: 0.45013704779557884
purpose: []
