name: Laura Gilchrist
favicon: null
layout_spectrum: 0
typography_spectrum: 0.61102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#120a15'
    - '#b47100'
    - '#f62c0c'
    - '#345ec5'
  brandStrength: 0.6875
  lightness: 0.5881772506982088
  saturation: 0.375
  rhythmicContrast: 0.45013704779557884
purpose: []
